CREATE DATABASE IF NOT EXISTS scanner_db;
USE scanner_db;

CREATE TABLE IF NOT EXISTS scans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    target_url VARCHAR(255) NOT NULL,
    report TEXT NOT NULL,
    scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);